CREATE TABLE IF NOT EXISTS pikobar_staging (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tanggal DATE,
    kode_prov BIGINT,
    nama_prov VARCHAR(255),
    kode_kab BIGINT,
    nama_kab VARCHAR(255),
    suspect_diisolasi INT,
    suspect_discarded INT,
    SUSPECT INT,
    closecontact_dikarantina INT,
    closecontact_discarded INT,
    CLOSECONTACT INT,
    probable_diisolasi INT,
    probable_discarded INT,
    PROBABLE INT,
    CONFIRMATION INT,
    confirmation_selesai INT,
    confirmation_meninggal INT,
    suspect_meninggal INT,
    closecontact_meninggal INT,
    probable_meninggal INT,
    PRIMARY KEY (id)
)